resourceType: SubscriptionTopic
id: us-core-problems-and-health-concerns
url: http://hl7.org/fhir/us/core/SubscriptionTopic/us-core-problems-and-health-concerns
version: 0.0.0
name: USCoreProblemsAndHealthConcernsSubscriptionTopic
title: US Core Problems And Health Concerns Subscription Topic
status: active
date: '2024-08-16'
description: This topic allows subscribers to receive notifications for Problems And
  Health Concerns events represented by US Core nan, including create, update, and
  delete interactions.
trigger:
- description: Trigger on Problems And Health Concerns events
  resource: .nan
  supportedInteraction:
  - create
  - update
  - delete
  fhirPathCriteria: '%previous.empty() or %current.empty() or %previous != %current'
  canFilterBy:
  - description: Filter by patient
    filterParameter: patient
